version: "3.9"
services:
  db:
    image: mysql
    restart: always
    container_name: db
    volumes:
    - ./database:/var/lib/mysql
    ports:
    - 2021:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practice
      MYSQL_USER: student
      MYSQL_PASSWORD: 123

  spring:
    build: .
    container_name: spring
    restart: always
    depends_on:
      - db
    ports:
    - 8080:8080